### ISSUE TITLE
Latest version of resolve-pathname broke urljoin.js

### ISSUE THREAD

**Issue by zhouzi** [GitbookIO/urljoin.js#2]
`resolve-pathname` has been released as `2.2.0`, which introduces ES6 exports. While `urljoin.js` still works in a NodeJS environment, it won't work when bundled with Webpack. That's because Webpack prefers to load the file referenced in the `package.json`'s `"module"` which is an ES6 version. The result is that `require('resolve-pathname')` resolves to `{ default: Function }`.

Related discussions:

* https://github.com/webpack/webpack/issues/5756
* https://github.com/webpack/webpack/issues/4742

We can whether change the version `urljoin.js` depends on (from `resolve-pathname@^2.1.0` to `resolve-pathname@2.1.0`) or rewrite it as ES6 and publish a version compiled with Webpack.

**Comment by donaldpipowitch** [comment]
> or rewrite it as ES6 and publish a version compiled with Webpack.

That sounds nice.
